name: Frontend CI

on:
    push:
        paths:
            - 'apps/frontend/**'
    pull_request:
        paths:
            - 'apps/frontend/**'

jobs:
    build-and-test:
        name: Build and Test Frontend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apps/frontend
        
        strategy:
            matrix:
                node-version: [22.2]
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Set up Node.js 22.2
              uses: actions/setup-node@v4
              with:
                node-version: 22.2
                cache: 'npm'
            
            - name: Install dependencies
              run: npm ci
            
            - name: Lint
              run: npm run lint
            
            - name: Build
              run: npm run build
            
            - name: Run tests
              run: npm run test -- --coverage
            
            - name: Upload coverage report
              if: success()
              uses: actions/upload-artifact@v4
              with:
                name: frontend-coverage
                path: frontend/coverage